name       : font-noto-cjk
version    : '2.001'
release    : 2
source     :
    - https://github.com/googlefonts/noto-cjk/archive/NotoSansV2.001.tar.gz : 3b18859b3efe3ac36d8d5273e93cc07b61a9480ac09c5b52edf4dd8aaab74187
license    : OFL-1.1
component  : desktop.font
summary    : Noto CJK fonts
description: |
    Noto CJK fonts, supporting Simplified Chinese, Traditional Chinese, Japanese, and Korean.
install    : |
    install -D -m00644 *.ttc -t $installdir/usr/share/fonts/truetype/noto-cjk

    # Borrowed from ArchLinux
    install -D -m00644 $pkgfiles/70-noto-cjk.conf -t $installdir/usr/share/fonts/conf.d
