name       : font-noto-cjk
version    : 2017.06.01
release    : 1
source     :
    - https://github.com/googlei18n/noto-cjk/archive/v2017-06-01-serif-cjk-1-1.tar.gz : ea2e045310f10ebc01389ed2cb69929f02d1884873586356b35a1e277885298b
license    : OFL-1.1
component  : desktop.font
summary    : Noto CJK fonts
description: |
    Noto CJK fonts, supporting Simplified Chinese, Traditional Chinese, Japanese, and Korean.
install    : |
    install -D -m00644 *.ttc -t $installdir/usr/share/fonts/truetype/noto-cjk

    # Borrowed from ArchLinux
    install -D -m00644 $pkgfiles/70-noto-cjk.conf -t $installdir/usr/share/fonts/conf.d
